require('babel-runtime/regenerator');
//require('react-hot-loader/patch');
require('babel-register');
require('webpack-hot-middleware/client?reload=true');
//require('./main.css');
//require('./new_main.scss');
//require('./images/sky.jpg');
require('./index.html');
require('./app');